import type { NextPage } from "next";
import Link from "next/link";
import { capsFirstLetter } from "./[genre]";

import Head from "next/head";

const Home = (props: any) => {
  const { genres } = props;

  return (
    <div>
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {genres.map((genre: string) => {
        return (
          genre && (
            <ul key={genre}>
              <Link href={`/${genre}`}>
                <a>{capsFirstLetter(genre)}</a>
              </Link>
            </ul>
          )
        );
      })}
    </div>
  );
};

export const getStaticProps = async () => {
  const data: any = await fetch(
    "https://api.spotify.com/v1/recommendations/available-genre-seeds",
    {
      headers: {
        Authorization: `Bearer ${process.env.SPOTIFY_0AUTH_TOKEN}`,
      },
    }
  ).then((response) => response.json());

  return {
    props: {
      genres: data.genres,
    },
    // revalidate: 60,
  };
};

export default Home;
